name: Deploy to Hostinger

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies and build project
      - name: Install & Build
        run: |
          npm install
          npm run build
          # You can skip this if "output: export" already set in next.config.js
          # (next export runs automatically after build in that case)

      # Step 4: Deploy to Hostinger via FTP
      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/
          local-dir: out/
